function StimParamGui()
    % global h_gui% Create GUI figure

    h_gui = figure('Name', 'Experiment Parameters', ...
        'NumberTitle', 'off', ...
        'Position', [500 500 400 500], ...
        'MenuBar', 'none');

    % Sound Parameters Panel
    soundPanel = uipanel('Title', 'AM Parameters', ...
        'Position', [.05 .6 .9 .35],...
        'FontSize', 16);

    % Sound Frequency
    uicontrol('Parent', soundPanel, ...
        'Style', 'text', ...
        'String', 'Sound Frequency (Hz):', ...
        'Position', [10 120 150 20],...
        'FontSize', 14);
    hSoundFreq = uicontrol('Parent', soundPanel, ...
        'Style', 'edit', ...
        'String', '523', ...
        'Position', [170 120 100 20],...
        'FontSize', 14);

    % Sound Duration
    uicontrol('Parent', soundPanel, ...
        'Style', 'text', ...
        'String', 'Sound Duration (seconds):', ...
        'Position', [10 90 150 20],...
        'FontSize', 14);
    hSoundDur = uicontrol('Parent', soundPanel, ...
        'Style', 'edit', ...
        'String', '1', ...
        'Position', [170 90 100 20],...
        'FontSize', 14);

    % Sound Volume
    uicontrol('Parent', soundPanel, ...
        'Style', 'text', ...
        'String', 'Sound Volume (0-1):', ...
        'Position', [10 60 150 20],...
        'FontSize', 14);
    hSoundVol = uicontrol('Parent', soundPanel, ...
        'Style', 'edit', ...
        'String', '0.3', ...
        'Position', [170 60 100 20],...
        'FontSize', 14);

    % Vibration Parameters Panel
    vibrationPanel = uipanel('Title', 'Vibration Parameters', ...
        'Position', [.05 .2 .9 .35],...
        'FontSize', 16);

    % Min ITI
    uicontrol('Parent', vibrationPanel, ...
        'Style', 'text', ...
        'String', 'Minimum Trial Interval (seconds):', ...
        'Position', [10 120 150 20],...
        'FontSize', 14);
    hMinITI = uicontrol('Parent', vibrationPanel, ...
        'Style', 'edit', ...
        'String', '2', ...
        'Position', [170 120 100 20],...
        'FontSize', 14);

    % Max ITI
    uicontrol('Parent', vibrationPanel, ...
        'Style', 'text', ...
        'String', 'Maximum Trial Interval (seconds):', ...
        'Position', [10 90 150 20],...
        'FontSize', 14);
    hMaxITI = uicontrol('Parent', vibrationPanel, ...
        'Style', 'edit', ...
        'String', '3', ...
        'Position', [170 90 100 20],...
        'FontSize', 14);

    % Min Quiet Time
    uicontrol('Parent', vibrationPanel, ...
        'Style', 'text', ...
        'String', 'Minimum Quiet Time (seconds):', ...
        'Position', [10 60 150 20],...
        'FontSize', 14);
    hMinQuiet = uicontrol('Parent', vibrationPanel, ...
        'Style', 'edit', ...
        'String', '1', ...
        'Position', [170 60 100 20],...
        'FontSize', 14);

    % Max Quiet Time
    uicontrol('Parent', vibrationPanel, ...
        'Style', 'text', ...
        'String', 'Maximum Quiet Time (seconds):', ...
        'Position', [10 30 150 20],...
        'FontSize', 14);
    hMaxQuiet = uicontrol('Parent', vibrationPanel, ...
        'Style', 'edit', ...
        'String', '2', ...
        'Position', [170 30 100 20],...
        'FontSize', 14);

    % Start Button
    uicontrol('Style', 'pushbutton', ...
        'String', 'Set Stimulus', ...
        'Position', [100 50 200 30], ...
        'FontSize', 14, ...
        'Callback', @startExperiment);

    get_params()

    % Callback function for start button
    function startExperiment(~, ~)
        % Get all parameter values
        get_params()
        disp("Stimulus parameters set")
        % Close GUI
        % close(fig);
        
    end

    function get_params()
        StimParams.SoundFrequency = str2double(get(hSoundFreq, 'String'));
        StimParams.SoundDuration = str2double(get(hSoundDur, 'String'));
        StimParams.SoundVolume = str2double(get(hSoundVol, 'String'));
        StimParams.MinITI = str2double(get(hMinITI, 'String'));
        StimParams.MaxITI = str2double(get(hMaxITI, 'String'));
        StimParams.MinQuietTime = str2double(get(hMinQuiet, 'String'));
        StimParams.MaxQuietTime = str2double(get(hMaxQuiet, 'String'));

        guidata(h_gui, StimParams);
    end

    % Wait for GUI to close before continuing
    % uiwait(fig);
end