function StimParams = StimParamGui_test()
    % testing changes made to vibration freq and amp input and saving
    % Create handle structure
    h = struct();
    
    h_gui = figure('Name', 'Stimulus Parameter Setting', ...
        'NumberTitle', 'off', ...
        'Position', [500 100 1100 900], ...
        'MenuBar', 'none');

    % Session type selection (normalized)
    uicontrol('Style', 'text', ...
        'String', 'Session Type:', ...
        'Units', 'normalized', ...
        'Position', [0.06 0.94 0.18 0.03], ...
        'FontSize', 14);
    h.SessionType = uicontrol('Style', 'popup', ...
        'String', {'Multimodal', 'SoundOnly', 'VibrationOnly'}, ...
        'Units', 'normalized', ...
        'Position', [0.25 0.94 0.15 0.03], ...
        'FontSize', 14, ...
        'Callback', @sessionTypeChanged);

    % Stimulus Duration
    uicontrol('Style', 'text', ...
        'String', 'Stimulus Duration(ms):', ...
        'Units', 'normalized', ...
        'Position', [0.02 0.88 0.2 0.03],...
        'FontSize', 14);
    h.Duration = uicontrol('Style', 'edit', ...
        'String', '500', ...
        'Units', 'normalized', ...
        'Position', [0.25 0.88 0.18 0.03],...
        'FontSize', 14);
    

    % Ramp Time
    uicontrol('Style', 'text', ...
        'String', 'Ramp Time(ms):', ...
        'Units', 'normalized', ...
        'Position', [0.05 0.84 0.18 0.03],...
        'FontSize', 14);
    h.Ramp = uicontrol('Style', 'edit', ...
        'String', '10', ...
        'Units', 'normalized', ...
        'Position', [0.25 0.84 0.18 0.03],...
        'FontSize', 14);

    % Sound stimulus parameters panel (normalized)
    soundPanel = uipanel('Title', 'Sound Stimulus Parameters', ...
        'Units', 'normalized', ...
        'Position', [.05 .35 .45 .48],...
        'FontSize', 16);

    % Sound type selection with callback (normalized)
    uicontrol('Parent', soundPanel, ...
        'Style', 'text', ...
        'String', 'Sound Type:', ...
        'Units', 'normalized', ...
        'Position', [0.05 0.87 0.35 0.1],...
        'FontSize', 14);
    h.SoundType = uicontrol('Parent', soundPanel, ...
        'Style', 'popup', ...
        'String', {'AM Noise','Noise Burst',  'Click Train'}, ...
        'Units', 'normalized', ...
        'Position', [0.45 0.87 0.45 0.1],...
        'FontSize', 14,...
        'Callback', @soundTypeChanged);

    % Create parameter panels for each type (normalized)
    amPanel = uipanel('Parent', soundPanel,...
        'Title', 'AM Noise Parameters',...
        'Units', 'normalized', ...
        'Position', [0.05 0.03 0.9 0.84],...
        'Visible', 'on',...
        'FontSize', 12);

    clickPanel = uipanel('Parent', soundPanel,...
        'Title', 'Click Train Parameters',...
        'Units', 'normalized', ...
        'Position', [0.05 0.03 0.9 0.84],...
        'Visible', 'off',...
        'FontSize', 12);

    noisePanel = uipanel('Parent', soundPanel,...
        'Title', 'Noise Parameters',...
        'Units', 'normalized', ...
        'Position', [0.05 0.03 0.9 0.84],...
        'Visible', 'off',...
        'FontSize', 12);

    % Create controls for each panel
    createAMControls(amPanel);
    createClickControls(clickPanel);
    createNoiseControls(noisePanel);

    % Vibration panel (normalized)
    vibPanel = uipanel('Title', 'Vibration Stimulus Parameters', ...
        'Units', 'normalized', ...
        'Position', [.05 .08 .45 .25],...
        'FontSize', 16);
    vib_param = createVibrationControls(vibPanel);

    % Behavior parameters panel (normalized)
    behavePanel = uipanel('Title', 'Behavior Parameters', ...
        'Units', 'normalized', ...
        'Position', [.52 .08 .43 .90],...
        'FontSize', 16);
    createBehaviorControls(behavePanel);

    % Set button (normalized)
    uicontrol('Style', 'pushbutton', ...
        'String', 'Set Parameters', ...
        'Units', 'normalized', ...
        'Position', [0.4 0.02 0.2 0.05], ...
        'FontSize', 14, ...
        'Callback', @setStimParams);

    function sessionTypeChanged(~, ~)
        sessionType = get(h.SessionType, 'Value');
        
        % Get all controls in sound panel
        soundControls = findall(soundPanel, 'Type', 'uicontrol');
        % Get all controls in vibration panel
        vibControls = findall(vibPanel, 'Type', 'uicontrol');
        
        % Get duration controls
        durationControls = findall(h_gui, 'Tag', 'SepDurControl');
        
        switch sessionType
            case 1 % Multimodal
                % Enable all controls except duration controls
                set(soundControls, 'Enable', 'on');
                set(vibControls, 'Enable', 'on');
                set(durationControls, 'Enable', 'off');
                set(soundPanel, 'Title', 'Sound Stimulus Parameters');
                set(vibPanel, 'Title', 'Vibration Stimulus Parameters');
                
            case 2 % SoundOnly
                % Enable sound controls, disable vibration controls
                set(soundControls, 'Enable', 'on');
                set(vibControls, 'Enable', 'off');
                set(durationControls, 'Enable', 'off');
                set(soundPanel, 'Title', 'Sound Stimulus Parameters');
                set(vibPanel, 'Title', 'Vibration Stimulus Parameters (Disabled)');
                
            case 3 % VibrationOnly
                % Disable sound controls, enable vibration controls
                set(soundControls, 'Enable', 'off');
                set(vibControls, 'Enable', 'on');
                set(durationControls, 'Enable', 'off');
                set(soundPanel, 'Title', 'Sound Stimulus Parameters (Disabled)');
                set(vibPanel, 'Title', 'Vibration Stimulus Parameters');
        end
    end

    function soundTypeChanged(~, ~)
        type = get(h.SoundType, 'Value');
        set(amPanel, 'Visible', 'off');
        set(clickPanel, 'Visible', 'off');
        set(noisePanel, 'Visible', 'off');
        
        switch type
            case 1
                set(amPanel, 'Visible', 'on');
            case 2
                set(noisePanel, 'Visible', 'on');
            case 3
                set(clickPanel, 'Visible', 'on');
        end
    end

    function createAMControls(parent)
        % Intensity
        uicontrol('Parent', parent, ...
            'Style', 'text', ...
            'String', 'Intensity (dB SPL):', ...
            'Units', 'normalized', ...
            'Position', [0.05 0.88 0.42 0.08],...
            'FontSize', 14);
        h.AM.Intensity = uicontrol('Parent', parent, ...
            'Style', 'edit', ...
            'String', '[60]', ...
            'Units', 'normalized', ...
            'Position', [0.5 0.88 0.4 0.08],...
            'FontSize', 14);

        % Modulation Frequency
        uicontrol('Parent', parent, ...
            'Style', 'text', ...
            'String', 'ModFreq (Hz):', ...
            'Units', 'normalized', ...
            'Position', [0.05 0.77 0.4 0.08],...
            'FontSize', 14);
        h.AM.ModFreq = uicontrol('Parent', parent, ...
            'Style', 'edit', ...
            'String', '[10,20,50]', ...
            'Units', 'normalized', ...
            'Position', [0.5 0.77 0.4 0.08],...
            'FontSize', 14);

        % Modulation Depth
        uicontrol('Parent', parent, ...
            'Style', 'text', ...
            'String', 'ModDepth (0-1):', ...
            'Units', 'normalized', ...
            'Position', [0.05 0.66 0.4 0.08],...
            'FontSize', 14);
        h.AM.ModDepth = uicontrol('Parent', parent, ...
            'Style', 'edit', ...
            'String', '1', ...
            'Units', 'normalized', ...
            'Position', [0.5 0.66 0.4 0.08],...
            'FontSize', 14);

        % FreqMin
        uicontrol('Parent', parent, ...
            'Style', 'text', ...
            'String', 'FreqMin (Hz):', ...
            'Units', 'normalized', ...
            'Position', [0.05 0.55 0.4 0.08],...
            'FontSize', 14);
        h.AM.FreqMin = uicontrol('Parent', parent, ...
            'Style', 'edit', ...
            'String', '2000', ...
            'Units', 'normalized', ...
            'Position', [0.5 0.55 0.4 0.08],...
            'FontSize', 14);

        % FreqMax
        uicontrol('Parent', parent, ...
            'Style', 'text', ...
            'String', 'FreqMax (Hz):', ...
            'Units', 'normalized', ...
            'Position', [0.05 0.44 0.4 0.08],...
            'FontSize', 14);
        h.AM.FreqMax = uicontrol('Parent', parent, ...
            'Style', 'edit', ...
            'String', '40000', ...
            'Units', 'normalized', ...
            'Position', [0.5 0.44 0.4 0.08],...
            'FontSize', 14);

        % Transition Time
        uicontrol('Parent', parent, ...
            'Style', 'text', ...
            'String', 'TransTime (ms):', ...
            'Units', 'normalized', ...
            'Position', [0.05 0.33 0.4 0.08],...
            'FontSize', 14);
        h.AM.TransitionTime = uicontrol('Parent', parent, ...
            'Style', 'edit', ...
            'String', '500', ...
            'Units', 'normalized', ...
            'Position', [0.5 0.33 0.4 0.08],...
            'FontSize', 14);

        % Transition Duration
        uicontrol('Parent', parent, ...
            'Style', 'text', ...
            'String', 'TransDur (ms):', ...
            'Units', 'normalized', ...
            'Position', [0.05 0.22 0.4 0.08],...
            'FontSize', 14);
        h.AM.TransitionDuration = uicontrol('Parent', parent, ...
            'Style', 'edit', ...
            'String', '20', ...
            'Units', 'normalized', ...
            'Position', [0.5 0.22 0.4 0.08],...
            'FontSize', 14);

        % Logarithmic density
        uicontrol('Parent', parent, ...
            'Style', 'text', ...
            'String', 'Log Density:', ...
            'Units', 'normalized', ...
            'Position', [0.05 0.11 0.4 0.08],...
            'FontSize', 14);
        h.AM.LogDen = uicontrol('Parent', parent, ...
            'Style', 'popup', ...
            'String', {'Yes', 'No'}, ...
            'Units', 'normalized', ...
            'Position', [0.5 0.11 0.2 0.09],...
            'FontSize', 14);
        
        % Boundary Frequency
        uicontrol('Parent', parent, ...
            'Style', 'text', ...
            'String', 'Boundary Frequency (Hz):', ...
            'Units', 'normalized', ...
            'Position', [0.05 0.01 0.4 0.08],...
            'FontSize', 14);
        h.AM.BoundaryFreq = uicontrol('Parent', parent, ...
            'Style', 'edit', ...
            'String', '400', ...
            'Units', 'normalized', ...
            'Position', [0.5 0.01 0.4 0.08],...
            'FontSize', 14);

        % Duration
        uicontrol('Parent', parent, ...
            'Style', 'text', ...
            'String', 'Duration (ms):', ...
            'Units', 'normalized', ...
            'Position', [0.05 0.33 0.4 0.08],...
            'FontSize', 14);
        h.AM.Duration = uicontrol('Parent', parent, ...
            'Style', 'edit', ...
            'String', '500', ...
            'Units', 'normalized', ...
            'Position', [0.5 0.33 0.4 0.08],...
            'FontSize', 14,...
            'Enable', 'off',...
            'Tag', 'SepDurControl');

    end

    function createClickControls(parent)
        % Click controls structure
        h.Click = struct();
        
        % Duration
        uicontrol('Parent', parent, ...
            'Style', 'text', ...
            'String', 'Duration (ms):', ...
            'Units', 'normalized', ...
            'Position', [0.05 0.85 0.4 0.1],...
            'FontSize', 14);
        h.Click.Duration = uicontrol('Parent', parent, ...
            'Style', 'edit', ...
            'String', '500', ...
            'Units', 'normalized', ...
            'Position', [0.6 0.85 0.3 0.1],...
            'FontSize', 14,...
            'Enable', 'off',...
            'Tag', 'SepDurControl');

        % Click Balance
        uicontrol('Parent', parent, ...
            'Style', 'text', ...
            'String', 'Click Balance:', ...
            'Units', 'normalized', ...
            'Position', [0.05 0.72 0.4 0.1],...
            'FontSize', 14);
        h.Click.Balance = uicontrol('Parent', parent, ...
            'Style', 'edit', ...
            'String', '0', ...
            'Units', 'normalized', ...
            'Position', [0.6 0.72 0.3 0.1],...
            'FontSize', 14);

        % Click Rate
        uicontrol('Parent', parent, ...
            'Style', 'text', ...
            'String', 'Click Rate (Hz):', ...
            'Units', 'normalized', ...
            'Position', [0.05 0.6 0.4 0.1],...
            'FontSize', 14);
        h.Click.Rate = uicontrol('Parent', parent, ...
            'Style', 'edit', ...
            'String', '10', ...
            'Units', 'normalized', ...
            'Position', [0.6 0.6 0.3 0.1],...
            'FontSize', 14);

        % Click Amplitude
        uicontrol('Parent', parent, ...
            'Style', 'text', ...
            'String', 'Click Amplitude (0-1):', ...
            'Units', 'normalized', ...
            'Position', [0.05 0.48 0.5 0.1],...
            'FontSize', 14);
        h.Click.Amplitude = uicontrol('Parent', parent, ...
            'Style', 'edit', ...
            'String', '0.5', ...
            'Units', 'normalized', ...
            'Position', [0.6 0.48 0.3 0.1],...
            'FontSize', 14);

        % Mask Intensity
        uicontrol('Parent', parent, ...
            'Style', 'text', ...
            'String', 'Mask Intensity (0-1):', ...
            'Units', 'normalized', ...
            'Position', [0.05 0.36 0.5 0.1],...
            'FontSize', 14);
        h.Click.MaskIntensity = uicontrol('Parent', parent, ...
            'Style', 'edit', ...
            'String', '0.1', ...
            'Units', 'normalized', ...
            'Position', [0.6 0.36 0.3 0.1],...
            'FontSize', 14);
    end

    function createNoiseControls(parent)
        % Noise controls structure
        h.Noise = struct();
        
        % Duration
        uicontrol('Parent', parent, ...
            'Style', 'text', ...
            'String', 'Duration (ms):', ...
            'Units', 'normalized', ...
            'Position', [0.05 0.85 0.4 0.1],...
            'FontSize', 14);
        h.Noise.Duration = uicontrol('Parent', parent, ...
            'Style', 'edit', ...
            'String', '500', ...
            'Units', 'normalized', ...
            'Position', [0.5 0.85 0.4 0.1],...
            'FontSize', 14,...
            'Enable', 'off',...
            'Tag', 'SepDurControl');

        % Intensity
        uicontrol('Parent', parent, ...
            'Style', 'text', ...
            'String', 'Level (dB):', ...
            'Units', 'normalized', ...
            'Position', [0.05 0.72 0.4 0.1],...
            'FontSize', 14);
        h.Noise.Level = uicontrol('Parent', parent, ...
            'Style', 'edit', ...
            'String', '0', ...
            'Units', 'normalized', ...
            'Position', [0.5 0.72 0.4 0.1],...
            'FontSize', 14);

        % Low Frequency
        uicontrol('Parent', parent, ...
            'Style', 'text', ...
            'String', 'Low Freq (Hz):', ...
            'Units', 'normalized', ...
            'Position', [0.05 0.6 0.4 0.1],...
            'FontSize', 14);
        h.Noise.FreqMin = uicontrol('Parent', parent, ...
            'Style', 'edit', ...
            'String', '1000', ...
            'Units', 'normalized', ...
            'Position', [0.5 0.6 0.4 0.1],...
            'FontSize', 14);

        % High Frequency
        uicontrol('Parent', parent, ...
            'Style', 'text', ...
            'String', 'High Freq (Hz):', ...
            'Units', 'normalized', ...
            'Position', [0.05 0.48 0.4 0.1],...
            'FontSize', 14);
        h.Noise.FreqMax = uicontrol('Parent', parent, ...
            'Style', 'edit', ...
            'String', '20000', ...
            'Units', 'normalized', ...
            'Position', [0.5 0.48 0.4 0.1],...
            'FontSize', 14);

        % Logarithmic density
        uicontrol('Parent', parent, ...
            'Style', 'text', ...
            'String', 'Log Density:', ...
            'Units', 'normalized', ...
            'Position', [0.05 0.36 0.4 0.1],...
            'FontSize', 14);
        h.Noise.LogDen = uicontrol('Parent', parent, ...
            'Style', 'popup', ...
            'String', {'Yes', 'No'}, ...
            'Units', 'normalized', ...
            'Position', [0.5 0.36 0.2 0.1],...
            'FontSize', 14);
    end

    function vib_param = createVibrationControls(parent)
    % createVibrationControls - Create vibration control UI elements
    % Input: parent - parent figure/panel handle
    
    % Get parent figure handle
    fig = ancestor(parent, 'figure');
    
    % Initialize data structure in guidata
    data = struct();
    data.stim = struct('freq', {}, 'amp', {});
    guidata(fig, data);
    data_ready = false; % if data is ready

    % Create UI controls (store handles as local variables, not in h.Vib)
    
    % Waveform Type
    uicontrol('Parent', parent, ...
        'Style', 'text', ...
        'String', 'Waveform', ...
        'Units', 'normalized', ...
        'Position', [0.005 0.85 0.22 0.11],...
        'FontSize', 14);
    
    Vib_Type = uicontrol('Parent', parent, ...
        'Style', 'popup', ...
        'String', {'BiSine', 'UniSine', 'Square'}, ...
        'Units', 'normalized', ...
        'Position', [0.25 0.85 0.2 0.11],...
        'FontSize', 14);

    % Boundary Frequency
    uicontrol('Parent', parent, ...
        'Style', 'text', ...
        'String', 'Boundary Freq (Hz):', ...
        'Units', 'normalized', ...
        'Position', [0.5 0.85 0.35 0.11],...
        'FontSize', 14);
    
    Vib_BoundaryFreq = uicontrol('Parent', parent, ...
        'Style', 'edit', ...
        'String', '250', ...
        'Units', 'normalized', ...
        'Position', [0.85 0.85 0.15 0.11],...
        'FontSize', 14);

    % Frequency input
    uicontrol('Parent', parent, ...
              'Style', 'text', ...
              'String', 'Freq (Hz):', ...
              'Units', 'normalized', ...
              'Position', [0.05 0.65 0.2 0.13], ...
              'HorizontalAlignment', 'left',...
              'FontSize', 12);
    
    Vib_edit_freq = uicontrol('Parent', parent, ...
                            'Style', 'edit', ...
                            'Units', 'normalized', ...
                            'Position', [0.25 0.65 0.15 0.13], ...
                            'FontSize', 12,...
                            'String', '', ...
                            'Callback', @edit_freq_Callback);
    
    % Amplitude input
    uicontrol('Parent', parent, ...
              'Style', 'text', ...
              'String', 'Amp (0-1):', ...
              'Units', 'normalized', ...
              'Position', [0.43 0.65 0.18 0.13], ...
              'FontSize', 12,...
              'HorizontalAlignment', 'left');
    
    Vib_edit_amp = uicontrol('Parent',parent, ...
                           'Style', 'edit', ...
                           'Units', 'normalized', ...
                           'Position', [0.6 0.65 0.18 0.13], ...
                           'FontSize', 12,...
                           'String', '', ...
                           'Callback', @edit_amp_Callback);
    
    % Add button
    Vib_btn_add = uicontrol('Parent', parent, ...
                          'Style', 'pushbutton', ...
                          'String', 'Add Stim', ...
                          'Units', 'normalized', ...
                          'Position', [0.82 0.65 0.17 0.15], ...
                          'Callback', @btn_add_Callback, ...
                          'FontSize', 12,...
                          'Enable', 'off');
    
    % Validation status
    Vib_txt_status = uicontrol('Parent', parent, ...
                             'Style', 'text', ...
                             'String', 'Enter frequency and amplitude', ...
                             'Units', 'normalized', ...
                             'Position', [0.68 0.4 0.3 0.2], ...
                             'FontSize', 10,...
                             'HorizontalAlignment', 'left', ...
                             'ForegroundColor', [0.5, 0.5, 0.5]);
    
    % Listbox to display added pairs
    uicontrol('Parent', parent, ...
              'Style', 'text', ...
              'String', 'Added Stimulus (sorted by Freq/Amp):', ...
              'Units', 'normalized', ...
              'Position', [0.05 0.55 0.5 0.08], ...
              'FontSize', 10,...
              'HorizontalAlignment', 'left');
    
    Vib_listbox = uicontrol('Parent', parent, ...
                          'Style', 'listbox', ...
                          'Units', 'normalized', ...
                          'Position',  [0.05 0.01 0.6 0.54], ...
                          'String', {}, ...
                          'FontSize', 10,...
                          'Value', 1, ...
                          'BackgroundColor', [1, 1, 1]);
    
    % Delete button
    Vib_btn_delete = uicontrol('Parent', parent, ...
                             'Style', 'pushbutton', ...
                             'String', 'Delete Selected', ...
                             'Units', 'normalized', ...
                             'Position', [0.7 0.2 0.25 0.13], ...
                             'FontSize', 12,...
                             'Callback', @btn_delete_Callback, ...
                             'Enable', 'off');
    
    % Done button
    uicontrol('Parent', parent, ...
                           'Style', 'pushbutton', ...
                           'String', 'Done', ...
                           'Units', 'normalized', ...
                           'Position', [0.7 0.05 0.25 0.13], ...
                           'FontSize', 12,...
                           'Callback', @btn_done_Callback);
    
    % initial value
    vib_param = struct('stim', struct('freq', {}, 'amp', {}));
    vib_param.vibType = 1;
    vib_param.vibTypeName = {'BiSine', 'UniSine', 'Square'};
    vib_param.BoundaryFreq = 250;

    % === Nested Callback Functions ===
    function edit_freq_Callback(~, ~)
        validate_inputs();
    end

    function edit_amp_Callback(~, ~)
        validate_inputs();
    end

    function validate_inputs()
        freq_str = get(Vib_edit_freq, 'String');
        amp_str = get(Vib_edit_amp, 'String');

        status_color = [0.5, 0.5, 0.5];
        add_enabled = false;
        
        if isempty(freq_str) || isempty(amp_str)
            status_text = 'Please enter both frequency and amplitude';
        else
            freq = str2double(freq_str);
            if isnan(freq) || mod(freq,1)~=0 || freq<=0
                status_text = 'Frequency must be positive integer';
                status_color = [1,0,0];
            else
                amp = str2double(amp_str);
                if isnan(amp) || amp<0 || amp>1
                    status_text = 'Amplitude must be between 0-1';
                    status_color = [1,0,0];
                else
                    status_text = sprintf('Valid: %d Hz, %.4f', freq, amp);
                    status_color = [0,0.5,0];
                    add_enabled = true;
                end
            end
        end
        
        set(Vib_txt_status, 'String', status_text, 'ForegroundColor', status_color);
        set(Vib_btn_add, 'Enable', bool_to_on_off(add_enabled));
    end

    function btn_add_Callback(~, ~)
        % Get data from figure's guidata
        data = guidata(fig);
        
        freq = round(str2double(get(Vib_edit_freq, 'String')));
        amp = str2double(get(Vib_edit_amp, 'String'));
        
        % Add new pair
        new_pair.freq = freq;
        new_pair.amp = amp;
        
        if isempty(data.stim)
            data.stim = new_pair;
        else
            data.stim(end+1) = new_pair;
            data.stim = sort_pairs(data.stim);
        end
        
        % Save back to guidata
        guidata(fig, data);
        
        % Update UI
        set(Vib_txt_status, 'String', sprintf('Added: %d Hz, %.4f', freq, amp), ...
            'ForegroundColor', [0,0.5,0]);
        set(Vib_edit_freq, 'String', '');
        set(Vib_edit_amp, 'String', '');
        
        update_listbox();
        set(Vib_btn_delete, 'Enable', 'on');
        validate_inputs();
    end

    function btn_delete_Callback(~, ~)
        data = guidata(fig);
        
        selected = get(Vib_listbox, 'Value');
        
        if ~isempty(data.stim) && selected <= length(data.stim)
            freq = data.stim(selected).freq;
            amp = data.stim(selected).amp;
            
            choice = questdlg(sprintf('Delete %d Hz @ %.4f?', freq, amp), ...
                             'Confirm Delete', 'Yes', 'No', 'No');
            
            if strcmp(choice, 'Yes')
                data.stim(selected) = [];
                guidata(fig, data);
                
                update_listbox();
                
                if isempty(data.stim)
                    set(Vib_btn_delete, 'Enable', 'off');
                end
                
                set(Vib_txt_status, 'String', sprintf('Deleted %d Hz @ %.4f', freq, amp), ...
                    'ForegroundColor', [0.5,0.5,0.5]);
            end
        end
    end
    
    % === result to be passed out to main GUI ===
    function btn_done_Callback(~, ~)   
        data = guidata(fig);

        % Display final data
        if isempty(data.stim)
            set(Vib_txt_status, 'String', sprintf('Stimulus not set !\n (￣へ￣)'), ...
                     'fontsize', 12,...
                    'ForegroundColor', [1, 0, 0]);
        else
            set(Vib_txt_status, 'String', sprintf('Stimulus set !\n (◕‿◕✿)'), ...
                'fontsize', 12,...
                'ForegroundColor', [0, 0.8, 0]);
            result = struct();
            result.vibType = get(Vib_Type, 'Value');
            result.vibTypeName = get(Vib_Type, 'String');
            result.BoundaryFreq = str2double(get(Vib_BoundaryFreq, 'String'));
            result.stim = data.stim;

            set(parent, 'UserData', result);
            data_ready = true;
        end
    end

    function update_listbox()
        data = guidata(fig);
        
        if isempty(data.stim)
            set(Vib_listbox, 'String', {'<No stimulus added>'}, 'Value', 1);
        else
            display_str = cell(length(data.stim), 1);
            for i = 1:length(data.stim)
                display_str{i} = sprintf('Freq: %3d Hz, Amp: %.4f', ...
                    data.stim(i).freq, data.stim(i).amp);
            end
            set(Vib_listbox, 'String', display_str, 'Value', 1);
        end
    end

    function sorted = sort_pairs(pairs)
        [~, idx] = sort([pairs.freq]);
        sorted = pairs(idx);
        
        unique_freqs = unique([sorted.freq]);
        if length(unique_freqs) < length(sorted)
            temp = [];
            for f = unique_freqs
                mask = [sorted.freq] == f;
                freq_pairs = sorted(mask);
                [~, amp_idx] = sort([freq_pairs.amp]);
                temp = [temp, freq_pairs(amp_idx)];
            end
            sorted = temp;
        end
    end

    function str = bool_to_on_off(val)
        if val; str = 'on'; else; str = 'off'; end
    end
    

    end

    function createBehaviorControls(parent)
        % ITI parameters
        uicontrol('Parent', parent, ...
            'Style', 'text', ...
            'String', 'Inter-Trial Interval (ITI):', ...
            'Units', 'normalized', ...
            'Position', [0.01 0.95 0.55 0.03],...
            'FontSize', 14,...
            'FontWeight', 'bold');

        uicontrol('Parent', parent, ...
            'Style', 'text', ...
            'String', 'Minimum ITI (s):', ...
            'Units', 'normalized', ...
            'Position', [0.2 0.91 0.3 0.03],...
            'FontSize', 12);
        h.Behave.MinITI = uicontrol('Parent', parent, ...
            'Style', 'edit', ...
            'String', '2', ...
            'Units', 'normalized', ...
            'Position', [0.6 0.91 0.3 0.03],...
            'FontSize', 12);

        uicontrol('Parent', parent, ...
            'Style', 'text', ...
            'String', 'Maximum ITI (s):', ...
            'Units', 'normalized', ...
            'Position', [0.2 0.87 0.3 0.03],...
            'FontSize', 12);
        h.Behave.MaxITI = uicontrol('Parent', parent, ...
            'Style', 'edit', ...
            'String', '3', ...
            'Units', 'normalized', ...
            'Position', [0.6 0.87 0.3 0.03],...
            'FontSize', 12);

        % Quiet time parameters
        uicontrol('Parent', parent, ...
            'Style', 'text', ...
            'String', 'Quiet(No-lick) Time:', ...
            'Units', 'normalized', ...
            'Position', [0.01 0.83 0.5 0.03],...
            'FontSize', 14,...
            'FontWeight', 'bold');

        uicontrol('Parent', parent, ...
            'Style', 'text', ...
            'String', 'Minimum Quiet Time (s):', ...
            'Units', 'normalized', ...
            'Position', [0.05 0.79 0.5 0.03],...
            'FontSize', 12);
        h.Behave.MinQuietTime = uicontrol('Parent', parent, ...
            'Style', 'edit', ...
            'String', '1', ...
            'Units', 'normalized', ...
            'Position', [0.6 0.79 0.3 0.03],...
            'FontSize', 12);

        uicontrol('Parent', parent, ...
            'Style', 'text', ...
            'String', 'Maximum Quiet Time (s):', ...
            'Units', 'normalized', ...
            'Position', [0.05 0.75 0.5 0.03],...
            'FontSize', 12);
        h.Behave.MaxQuietTime = uicontrol('Parent', parent, ...
            'Style', 'edit', ...
            'String', '2', ...
            'Units', 'normalized', ...
            'Position', [0.6 0.75 0.3 0.03],...
            'FontSize', 12);

        % Response window parameters
        uicontrol('Parent', parent, ...
            'Style', 'text', ...
            'String', 'Response Window:', ...
            'Units', 'normalized', ...
            'Position', [0.01 0.71 0.5 0.03],...
            'FontSize', 14,...
            'FontWeight', 'bold');

        uicontrol('Parent', parent, ...
            'Style', 'text', ...
            'String', 'Response Window Duration (s):', ...
            'Units', 'normalized', ...
            'Position', [0.01 0.67 0.6 0.03],...
            'FontSize', 12);
        h.Behave.ResWin = uicontrol('Parent', parent, ...
            'Style', 'edit', ...
            'String', '5', ...
            'Units', 'normalized', ...
            'Position', [0.6 0.67 0.3 0.03],...
            'FontSize', 12);

        % Reward parameters
        uicontrol('Parent', parent, ...
            'Style', 'text', ...
            'String', 'Reward Settings:', ...
            'Units', 'normalized', ...
            'Position', [0.05 0.63 0.4 0.03],...
            'FontSize', 14,...
            'FontWeight', 'bold');

        uicontrol('Parent', parent, ...
            'Style', 'text', ...
            'String', 'Reward Amount (µL):', ...
            'Units', 'normalized', ...
            'Position', [0.05 0.59 0.5 0.03],...
            'FontSize', 12);
        h.Behave.RewardAmount = uicontrol('Parent', parent, ...
            'Style', 'edit', ...
            'String', '2', ...
            'Units', 'normalized', ...
            'Position', [0.6 0.59 0.3 0.03],...
            'FontSize', 12);
        
        % Number of Trials
        uicontrol('Parent',parent,...
            'Style', 'text', ...
            'String', 'Number of Trials & Catch Trials:', ...
            'Units', 'normalized', ...
            'Position', [0.01 0.55 0.75 0.03],...
            'FontSize', 14,...
            'FontWeight', 'bold');

        uicontrol('Parent', parent, ...
            'Style', 'text', ...
            'String', 'Number of Trials:', ...
            'Units', 'normalized', ...
            'Position', [0.2 0.51 0.3 0.03],...
            'FontSize', 12);
        h.Behave.NumTrials = uicontrol('Parent', parent, ...
            'Style', 'edit', ...
            'String', '150', ...
            'Units', 'normalized', ...
            'Position', [0.6 0.51 0.3 0.03],...
            'FontSize', 12);

        % Percentage of catch trials
        uicontrol('Parent', parent, ...
            'Style', 'text', ...
            'String', 'Catch Trial Proportion (0-1):', ...
            'Units', 'normalized', ...
            'Position', [0.02 0.47 0.5 0.03],...
            'FontSize', 12);
        h.Behave.PropCatch = uicontrol('Parent', parent, ...
            'Style', 'edit', ...
            'String', '0', ...
            'Units', 'normalized', ...
            'Position', [0.6 0.47 0.3 0.03],...
            'FontSize', 12);

        % Reward settings
        uicontrol('Parent', parent, ...
            'Style', 'text', ...
            'String', 'Reward Settings:', ...
            'Units', 'normalized', ...
            'Position', [0.01 0.43 0.5 0.03],...
            'FontSize', 14,...
            'FontWeight', 'bold');

        % High Freq spout
        uicontrol('Parent', parent, ...
            'Style', 'text', ...
            'String', '"High Freq" Spout:', ...
            'Units', 'normalized', ...
            'Position', [0.01 0.39 0.5 0.03],...
            'FontSize', 12);
        h.Behave.CorrectSpout = uicontrol('Parent', parent, ...
            'Style', 'popup', ...
            'String', {'left','right'}, ...
            'Units', 'normalized', ...
            'Position', [0.6 0.39 0.3 0.03],...
            'FontSize', 12);

        % Reward Probability
        uicontrol('Parent', parent, ...
            'Style', 'text', ...
            'String', 'Reward Probability(0-1):', ...
            'Units', 'normalized', ...
            'Position', [0.01 0.35 0.5 0.03],...
            'FontSize', 12);
        h.Behave.RewardProbability = uicontrol('Parent', parent, ...
            'Style', 'edit', ...
            'String', '1', ...
            'Units', 'normalized', ...
            'Position', [0.6 0.35 0.3 0.03],...
            'FontSize', 12);

        % Boundary Probability
        uicontrol('Parent', parent, ...
            'Style', 'text', ...
            'String', 'Boundary Probability(0-1):', ...
            'Units', 'normalized', ...
            'Position', [0.01 0.31 0.5 0.03],...
            'FontSize', 12);
        h.Behave.BoundaryProbability = uicontrol('Parent', parent, ...
            'Style', 'edit', ...
            'String', '0', ...
            'Units', 'normalized', ...
            'Position', [0.6 0.31 0.3 0.03],...
            'FontSize', 12);

        % Boundary Reward Probability
        uicontrol('Parent', parent, ...
            'Style', 'text', ...
            'String', 'Boundary Reward Probability(0-1):', ...
            'Units', 'normalized', ...
            'Position', [0 0.27 0.6 0.03],...
            'FontSize', 12);
        h.Behave.BoundaryRewardProbability = uicontrol('Parent', parent, ...
            'Style', 'edit', ...
            'String', '0', ...
            'Units', 'normalized', ...
            'Position', [0.6 0.27 0.3 0.03],...
            'FontSize', 12);

        % Error message display area
        h.ErrorMsg = uicontrol('Parent', parent, ...
            'Style', 'text', ...
            'String', 'Error Message will be displayed here', ...
            'Units', 'normalized', ...
            'Position', [0.02 0.01 0.96 0.15],...
            'FontSize', 12,...
            'ForegroundColor', 'red',...
            'HorizontalAlignment', 'left',...
            'BackgroundColor', [1 1 1]);
    end

    function setStimParams(~, ~)
        % Clear previous error message
        set(h.ErrorMsg, 'String', '');
        
        try
            % Get session type
            sessionType = get(h.SessionType, 'Value');
            sessionTypeStr = get(h.SessionType, 'String');
            StimParams.Session.Type = sessionType;
            StimParams.Session.TypeName = sessionTypeStr{sessionType};
            
            % get sound type
            soundType = get(h.SoundType, 'Value');
            soundTypeStr = get(h.SoundType, 'String');
            StimParams.Sound.Type = soundType;
            StimParams.Sound.TypeName = soundTypeStr{soundType};
            StimParams.Duration = str2double(get(h.Duration, 'String')); % ms
            StimParams.Ramp = str2double(get(h.Ramp, 'String')); % ms
            
            % Only get sound parameters if not VibrationOnly
            if sessionType ~= 3
                switch soundType
                    case 1 % AM Noise
                        % StimParams.Sound.Duration = str2double(get(h.AM.Duration, 'String'));
                        StimParams.Sound.Noise.Intensity = str2num(get(h.AM.Intensity, 'String'),Evaluation="restricted");
                        StimParams.Sound.Noise.FreqMin = str2double(get(h.AM.FreqMin, 'String'));
                        StimParams.Sound.Noise.FreqMax = str2double(get(h.AM.FreqMax, 'String'));
                        if get(h.AM.LogDen, 'Value') == 1
                            StimParams.Sound.Noise.LogDen = 1;
                        else
                            StimParams.Sound.Noise.LogDen = 0;
                        end
                        StimParams.Sound.AM.Carrier = 'Noise';
                        StimParams.Sound.AM.ModFreq = str2num(get(h.AM.ModFreq, 'String'),Evaluation="restricted");
                        StimParams.Sound.AM.ModDepth = str2num(get(h.AM.ModDepth, 'String'),Evaluation="restricted");
                        StimParams.Sound.AM.TransitionTime = str2double(get(h.AM.TransitionTime, 'String'));
                        StimParams.Sound.AM.TransitionDuration = str2double(get(h.AM.TransitionDuration, 'String'));
                        StimParams.Sound.Ramp = str2double(get(h.Ramp, 'String')); % ms


                    case 2 % NoiseBurst
                        % StimParams.Sound.Duration = str2double(get(h.Noise.Duration, 'String'));
                        StimParams.Sound.Noise.FreqMin = str2double(get(h.Noise.FreqMin, 'String'));
                        StimParams.Sound.Noise.FreqMax = str2double(get(h.Noise.FreqMax, 'String'));
                        if get(h.Noise.LogDen, 'Value') == 1    
                            StimParams.Sound.Noise.LogDen = 1;
                        else
                            StimParams.Sound.Noise.LogDen = 0;
                        end
                        % Handle Noise Level input
                        levelStr = get(h.Noise.Level, 'String');
                        try
                            % First try to handle comma-separated numbers
                            if contains(levelStr, ',')
                                % Split by comma and convert to numbers
                                parts = strsplit(levelStr, ',');
                                parts = cellfun(@str2double, parts, 'UniformOutput', false);
                                if all(~cellfun(@isnan, parts))
                                    StimParams.Sound.Noise.Level = cell2mat(parts)';
                                else
                                    error('Invalid number format in comma-separated list');
                                end
                            else
                                % Try to evaluate the string as a MATLAB expression
                                levelValue = eval(levelStr);
                                % Convert to column vector if it's a row vector
                                if size(levelValue, 1) == 1
                                    levelValue = levelValue';
                                end
                                StimParams.Sound.Noise.Level = levelValue;
                            end
                        catch
                            % If evaluation fails, try to parse as a range
                            try
                                % Split the string by ':'
                                parts = strsplit(levelStr, ':');
                                % Convert all parts to numbers
                                parts = cellfun(@str2double, parts, 'UniformOutput', false);
                                % Check if all parts are valid numbers
                                if all(~cellfun(@isnan, parts))
                                    switch length(parts)
                                        case 1
                                            % Single value
                                            StimParams.Sound.Noise.Level = parts{1};
                                        case 2
                                            % Start:End (default step = 1)
                                            StimParams.Sound.Noise.Level = (parts{1}:parts{2})';
                                        case 3
                                            % Start:Step:End
                                            StimParams.Sound.Noise.Level = (parts{1}:parts{2}:parts{3})';
                                        otherwise
                                            % Multiple values separated by colons
                                            StimParams.Sound.Noise.Level = cell2mat(parts)';
                                    end
                                else
                                    error('Invalid number format in range');
                                end
                            catch
                                error(sprintf(['Invalid Noise Level format. Please use one of these formats:' newline ...
                                    '- Comma separated: "4,5,10"' newline ...
                                    '- Space separated: "[4 5 10]"' newline ...
                                    '- Range with step: "0:5:60"']));
                            end
                        end
                        
                    case 3 % Click Train
                        % StimParams.Sound.Duration = str2double(get(h.Click.Duration, 'String'));
                        StimParams.Sound.Click.Balance = str2double(get(h.Click.Balance, 'String'));
                        StimParams.Sound.Click.Rate = str2double(get(h.Click.Rate, 'String'));
                        StimParams.Sound.Click.Amplitude = str2double(get(h.Click.Amplitude, 'String'));
                        StimParams.Sound.Click.MaskIntensity = str2double(get(h.Click.MaskIntensity, 'String'));
                end
            end
            
            % Only get vibration parameters if not SoundOnly
            if sessionType ~= 2
                % Vibration parameters
                vib_param = get(vibPanel, 'UserData');
                 if ~isfield(vib_param, 'stim') || isempty(vib_param.stim)
                        error('Please set vibration parameters first!');
                 else
                    vibType = vib_param.vibType;
                    StimParams.Vibration.Type = vib_param.vibType;
                    StimParams.Vibration.TypeName = vib_param.vibTypeName{vibType};
                    StimParams.Vibration.BoundaryFreq = vib_param.BoundaryFreq;
                    StimParams.Vibration.Stimulus = vib_param.stim;
                    % StimParams.Vibration.Duration = str2double(get(h.Vib.Duration, 'String'));
                 end
            end

            % Behavior parameters
            StimParams.Behave.MinITI = str2double(get(h.Behave.MinITI, 'String'));
            StimParams.Behave.MaxITI = str2double(get(h.Behave.MaxITI, 'String'));
            StimParams.Behave.MinQuietTime = str2double(get(h.Behave.MinQuietTime, 'String'));
            StimParams.Behave.MaxQuietTime = str2double(get(h.Behave.MaxQuietTime, 'String'));
            StimParams.Behave.ResWin = str2double(get(h.Behave.ResWin, 'String'));
            StimParams.Behave.RewardAmount = str2double(get(h.Behave.RewardAmount, 'String'));
            StimParams.Behave.NumTrials = str2double(get(h.Behave.NumTrials, 'String'));
            StimParams.Behave.BoundaryProbability = str2double(get(h.Behave.BoundaryProbability, 'String'));
            StimParams.Behave.BoundaryRewardProbability = str2double(get(h.Behave.BoundaryRewardProbability, 'String'));
            
            % Validate catch trial proportion
            propCatch = str2double(get(h.Behave.PropCatch, 'String'));
            if propCatch < 0 || propCatch > 1
                error('Catch trial proportion must be between 0 and 1');
            end
            StimParams.Behave.PropCatch = propCatch;

            % Validate reward probability
            rewardProb = str2double(get(h.Behave.RewardProbability, 'String'));
            if isnan(rewardProb) || rewardProb < 0 || rewardProb > 1
                error('Reward probability must be a number between 0 and 1');
            end
            StimParams.Behave.RewardProbability = rewardProb;

            % Get correct spout selection
            correctSpout = get(h.Behave.CorrectSpout, 'Value');
            correctSpoutStr = get(h.Behave.CorrectSpout, 'String');
            StimParams.Behave.CorrectSpout = correctSpout;
            StimParams.Behave.CorrectSpoutName = correctSpoutStr{correctSpout};

            % Save and display parameters
            guidata(h_gui, StimParams);
            disp('Stimulus parameters set:')
            disp(StimParams)
            
            uiresume(h_gui);
        catch ME
            % Display error message in the error area
            set(h.ErrorMsg, 'String', ME.message);
        end
    end

    uiwait(h_gui);
    close(h_gui);
end