% A GUI for controlling two valves (left/right) to dispense water droplets
% Features:
% - Set dose volume (μL) and number of drops for each valve
% - Real-time cumulative volume display (left, right, and total)
% - Clear counters function
% - Status feedback during operation

% Create main window
fig = uifigure('Name', 'Liquid Dispensing Control System', ...
              'Position', [500 300 600 550], ...
              'Resize', 'off');

% Initialize counter variables
global leftCount rightCount totalCount
global leftDoseField leftDropField rightDoseField rightDropField leftCountLabel rightCountLabel totalCountLabel statusLabel
leftCount = 0;
rightCount = 0;
totalCount = 0;


% Left control panel
leftPanel = uipanel(fig, 'Title', 'Left Valve (Valve 1)', ...
                   'Position', [50 300 220 200], ...
                   'FontSize', 14, ...
                   'FontWeight', 'bold');

% Left Volume setting
uilabel(leftPanel, 'Position', [20 140 100 20], ...
       'Text', 'Volume (μL):', ...
       'FontSize', 12);

leftDoseField = uieditfield(leftPanel, 'numeric', ...
                           'Position', [120 140 80 25], ...
                           'Value', 4, ...
                           'Limits', [0.1 1000], ...
                           'FontSize', 12);

% Left number of drops setting
uilabel(leftPanel, 'Position', [20 100 100 20], ...
       'Text', 'Number of drops:', ...
       'FontSize', 12);

leftDropField = uieditfield(leftPanel, 'numeric', ...
                            'Position', [120 100 80 25], ...
                            'Value', 1, ...
                            'Limits', [1 100], ...
                            'FontSize', 12);

% Left dispense button
leftButton = uibutton(leftPanel, 'push', ...
                     'Position', [20 50 180 30], ...
                     'Text', 'Left Dispense', ...
                     'FontSize', 14, ...
                     'FontWeight', 'bold', ...
                     'BackgroundColor', [0.3 0.7 0.9], ...
                     'ButtonPushedFcn', @(btn,event) leftDispense());

% Right control panel
rightPanel = uipanel(fig, 'Title', 'Right Valve (Valve 2)', ...
                    'Position', [330 300 220 200], ...
                    'FontSize', 14, ...
                    'FontWeight', 'bold');

% Right Volume setting
uilabel(rightPanel, 'Position', [20 140 100 20], ...
       'Text', 'Volume (μL):', ...
       'FontSize', 12);

rightDoseField = uieditfield(rightPanel, 'numeric', ...
                            'Position', [120 140 80 25], ...
                            'Value', 4, ...
                            'Limits', [0.1 1000], ...
                            'FontSize', 12);

% Right number of drops setting
uilabel(rightPanel, 'Position', [20 100 100 20], ...
       'Text', 'Number of drops:', ...
       'FontSize', 12);

rightDropField = uieditfield(rightPanel, 'numeric', ...
                             'Position', [120 100 80 25], ...
                             'Value', 1, ...
                             'Limits', [1 100], ...
                             'FontSize', 12);

% Right dispense button
rightButton = uibutton(rightPanel, 'push', ...
                      'Position', [20 50 180 30], ...
                      'Text', 'Right Dispense', ...
                      'FontSize', 14, ...
                      'FontWeight', 'bold', ...
                      'BackgroundColor', [0.3 0.7 0.9], ...
                      'ButtonPushedFcn', @(btn,event) rightDispense());

% Counter display panel
countPanel = uipanel(fig, 'Title', 'Cumulative Dispensed Volume', ...
                    'Position', [50 70 500 200], ...
                    'FontSize', 14, ...
                    'FontWeight', 'bold');

% Left counter display
uilabel(countPanel, 'Position', [80 130 100 30], ...
       'Text', 'Left Total:', ...
       'FontSize', 16, ...
       'FontWeight', 'bold');

leftCountLabel = uilabel(countPanel, 'Position', [200 130 100 30], ...
                        'Text', '0 μL', ...
                        'FontSize', 20, ...
                        'FontWeight', 'bold', ...
                        'FontColor', [0 0.5 0]);

% Right counter display
uilabel(countPanel, 'Position', [300 130 100 30], ...
       'Text', 'Right Total:', ...
       'FontSize', 16, ...
       'FontWeight', 'bold');

rightCountLabel = uilabel(countPanel, 'Position', [420 130 100 30], ...
                         'Text', '0 μL', ...
                         'FontSize', 20, ...
                         'FontWeight', 'bold', ...
                         'FontColor', [0 0.5 0]);

% Total counter display
uilabel(countPanel, 'Position', [150 80 100 30], ...
       'Text', 'Total:', ...
       'FontSize', 16, ...
       'FontWeight', 'bold', ...
       'FontColor', [0.5 0 0.5]);

totalCountLabel = uilabel(countPanel, 'Position', [250 80 100 30], ...
                         'Text', '0 μL', ...
                         'FontSize', 20, ...
                         'FontWeight', 'bold', ...
                         'FontColor', [0.5 0 0.5]);

% Clear button
clearButton = uibutton(countPanel, 'push', ...
                      'Position', [200 30 100 30], ...
                      'Text', 'Clear Counters', ...
                      'FontSize', 12, ...
                      'BackgroundColor', [0.9 0.9 0.9], ...
                      'ButtonPushedFcn', @(btn,event) clearCounters());

% Status display
statusLabel = uilabel(fig, 'Position', [50 20 500 30], ...
                     'Text', 'Ready', ...
                     'FontSize', 12, ...
                     'HorizontalAlignment', 'center', ...
                     'BackgroundColor', [0.95 0.95 0.95]);

% Set window close callback - FIXED: using a nested function that can access fig
fig.CloseRequestFcn = @(src,event) closeGUI(fig);

% Left dispense function
function leftDispense()
    global leftCount totalCount
    global leftDoseField leftDropField leftCountLabel totalCountLabel statusLabel
    try
        dose = leftDoseField.Value;
        drops = leftDropField.Value;
        
        statusLabel.Text = 'Left dispensing in progress...';
        statusLabel.BackgroundColor = [1 1 0.8];
        drawnow;
        
        % Call dispense function
        Dispense(1, dose, drops);
        
        % Update counters
        dispensedVolume = dose * drops;
        leftCount = leftCount + dispensedVolume;
        totalCount = totalCount + dispensedVolume;
        
        leftCountLabel.Text = [num2str(leftCount) ' μL'];
        totalCountLabel.Text = [num2str(totalCount) ' μL'];
        
        statusLabel.Text = sprintf('Left dispense complete: %.1f μL × %d', dose, drops);
        statusLabel.BackgroundColor = [0.8 1 0.8];
        
    catch ME
        statusLabel.Text = ['Error: ' ME.message];
        statusLabel.BackgroundColor = [1 0.8 0.8];
    end
end

% Right dispense function
function rightDispense()
    global rightCount totalCount
    global rightDoseField rightDropField rightCountLabel totalCountLabel statusLabel
    try
        dose = rightDoseField.Value;
        drops = rightDropField.Value;
        
        statusLabel.Text = 'Right dispensing in progress...';
        statusLabel.BackgroundColor = [1 1 0.8];
        drawnow;
        
        % Call dispense function
        Dispense(2, dose, drops);
        
        % Update counters
        dispensedVolume = dose * drops;
        rightCount = rightCount + dispensedVolume;
        totalCount = totalCount + dispensedVolume;
        
        rightCountLabel.Text = [num2str(rightCount) ' μL'];
        totalCountLabel.Text = [num2str(totalCount) ' μL'];
        
        statusLabel.Text = sprintf('Right dispense complete: %.1f μL × %d', dose, drops);
        statusLabel.BackgroundColor = [0.8 1 0.8];
        
    catch ME
        statusLabel.Text = ['Error: ' ME.message];
        statusLabel.BackgroundColor = [1 0.8 0.8]; 
    end
end

% Clear counters function
function clearCounters()
    global leftCount rightCount totalCount
    global leftCountLabel rightCountLabel totalCountLabel statusLabel
    leftCount = 0;
    rightCount = 0;
    totalCount = 0;
    leftCountLabel.Text = '0 μL';
    rightCountLabel.Text = '0 μL';
    totalCountLabel.Text = '0 μL';
    statusLabel.Text = 'Counters cleared';
    statusLabel.BackgroundColor = [0.95 0.95 0.95];
end

% Close GUI function - FIXED: now accepts fig as input argument
function closeGUI(fig)
    % Stop Bpod protocol
    try
        RunProtocol('Stop');
    catch
        % Ignore errors
    end
    delete(fig);
end