% Categorization protocol
% This protocol is used to categorize the stimuli into different categories by frequency
% Stimuli will be played in a random order, and the animal will be rewarded for licking the correct spout
function Categorization()
    global BpodSystem

    % Create trial manager object
    trialManager = BpodTrialManager;

    % Initialize HiFi module
    H = BpodHiFi('COM3');
    H.SamplingRate = 192000;

    % get parameters from StimParamGui
    StimParams = BpodSystem.ProtocolSettings.StimParams;
    NumTrials = StimParams.Behave.NumTrials;
    StimDur = StimParams.Duration/1000;

    % Save Protocol name and Subject name to Data.Info
    BpodSystem.Data.Info.ProtocolName = BpodSystem.GUIData.ProtocolName;
    BpodSystem.Data.Info.SubjectName = BpodSystem.GUIData.SubjectName;
    
    % Generate complete randomized StimTable (includes CorrectSide and Rewarded columns)
    StimTable = GenStimSeq(StimParams);
    
    % Generate LeftRightSeq structure for data consistency (similar to AntiBias)
    LeftRightSeq = GenLeftRightSeq(StimParams);

    % Load calibration table
    CalFile = 'Calibration Files\CalTable_20250923.mat';
    load(CalFile,'CalTable');

    % Setup default parameters
    S = struct;
    % use the behavior parameters from StimParamGui as default values
    S.GUI.MinITI = StimParams.Behave.MinITI; % seconds
    S.GUI.MaxITI = StimParams.Behave.MaxITI; % seconds
    S.GUI.MinQuietTime = StimParams.Behave.MinQuietTime; % seconds
    S.GUI.MaxQuietTime = StimParams.Behave.MaxQuietTime; % seconds
    S.GUI.RewardAmount = StimParams.Behave.RewardAmount; % µL
    S.GUI.ResWin = StimParams.Behave.ResWin; % seconds

    % Cut-off period for NoLick state
    CutOffPeriod = 60; % seconds

    % Initialize parameter GUI
    BpodParameterGUI('init', S);
    % Create update button
    uicontrol('Style', 'pushbutton', ...
        'String', 'Update Parameters', ...
        'Position', [160 240 150 30], ...  % [left bottom width height]
        'FontSize', 12, ...
        'Callback', @updateParams);

    % Initialize update flag
    updateFlag = false;

    % Update button callback function
    function updateParams(~, ~)
        updateFlag = true;
        disp('Parameters updated');
    end

    % Save the LeftRightSeq and StimParams to SessionData (similar to AntiBias)
    BpodSystem.Data.LeftRightSeq = LeftRightSeq;
    BpodSystem.Data.StimParams = StimParams;
    
    % Save complete randomized StimTable directly (already generated by GenStimSeq)
    BpodSystem.Data.StimTable = StimTable;
    
    % Initialize data arrays
    BpodSystem.Data.CorrectSide = [];
    BpodSystem.Data.IsCatchTrial = [];
    
    %% Initialize plots
    % Initialize the outcome plot with different trial types for left/right spouts
    trialTypes = ones(1, NumTrials); % Will be updated based on correctSide (1=left, 2=right, 3=boundary)
    outcomePlot = LiveOutcomePlot([1 2], {'Left Spout', 'Right Spout'}, trialTypes, NumTrials); % Create an instance of the LiveOutcomePlot GUI
    % Arg1 = trialTypeManifest, a list of possible trial types (1=left, 2=right).
    % Arg2 = trialTypeNames, a list of names for each trial type in trialTypeManifest
    % Arg3 = trialTypes, a list of integers denoting precomputed trial types in the session
    % Arg4 = nTrialsToShow, the number of trials to show
    outcomePlot.RewardStateNames = {'LeftReward', 'RightReward'}; % List of state names where reward was delivered
    outcomePlot.CorrectStateNames = {'LeftReward', 'RightReward'}; % States where correct response was made
    
    %% Initialize custom figure with layout matching MainAn_v2 combined figure
    % Layout: 3 rows x 3 columns
    % Row 1: PlotLickIntervals, PlotResLatency, PlotLickRaster
    % Row 2: PlotSessionSummary, PlotCDFHitRate, PlotBarResponse
    % Row 3: PlotHitResponseRate (centered), empty, empty
    customPlotFig = figure('Name', 'Behavior Analysis', 'Position', [100, 100, 1500, 800]);
    
    % Subplot 1: Session Summary (1,1) - left column, spans 2 rows
    summaryAx = subplot(3, 3, [1,4]);
    axis(summaryAx, 'off');
    
    % Subplot 2: Lick Intervals (1,2) - middle column, row 2
    lickIntervalAx = subplot(3, 3, 5);
    title(lickIntervalAx, 'Lick Intervals Distribution');
    xlabel(lickIntervalAx, 'Lick Interval (seconds)');
    ylabel(lickIntervalAx, 'Count');
    grid(lickIntervalAx, 'on');
    hold(lickIntervalAx, 'on');
    
    % Subplot 3: Response Latency (1,3) - middle column, row 3
    resLatencyAx = subplot(3, 3, 6);
    title(resLatencyAx, 'Response Latency Distribution');
    xlabel(resLatencyAx, 'Response Latency (seconds)');
    ylabel(resLatencyAx, 'Count');
    grid(resLatencyAx, 'on');
    hold(resLatencyAx, 'on');
    
    % Subplot 4: Lick Raster (2,1) - top 2 rows, spans 2 columns (split into 2 subplots)
    rasterAx1 = subplot(3, 3, 2);
    title(rasterAx1, 'Licks aligned to stimulus onset (full range)');
    xlabel(rasterAx1, 'Time re stim. onset (s)');
    ylabel(rasterAx1, 'Trial number');
    grid(rasterAx1, 'on');
    hold(rasterAx1, 'on');
    
    rasterAx2 = subplot(3, 3, 3);
    title(rasterAx2, 'Licks aligned to stimulus onset (response window)');
    xlabel(rasterAx2, 'Time re stim. onset (s)');
    ylabel(rasterAx2, 'Trial number');
    grid(rasterAx2, 'on');
    hold(rasterAx2, 'on');
    
    % Subplot 5: CDF Hit Rate (2,2) - middle column, row 3
    cdfHitRateAx = subplot(3, 3, 8);
    title(cdfHitRateAx, 'CDF of Hit Rate');
    xlabel(cdfHitRateAx, 'Reaction Time (s)');
    ylabel(cdfHitRateAx, 'Cumulative Proportion');
    grid(cdfHitRateAx, 'on');
    hold(cdfHitRateAx, 'on');
    
    % Subplot 6: Bar Response (2,3) - right column, row 2
    barResponseAx = subplot(3, 3, 7);
    title(barResponseAx, 'Response Rate by Condition');
    xlabel(barResponseAx, 'Condition');
    ylabel(barResponseAx, 'Response Rate');
    grid(barResponseAx, 'on');
    hold(barResponseAx, 'on');
    
    % Subplot 7: Hit Response Rate (3,2) - right column, row 3
    responseRateAx = subplot(3, 3, 9);
    title(responseRateAx, 'Hit Rate and Response Rate');
    xlabel(responseRateAx, 'Trial number');
    ylabel(responseRateAx, 'Rate');
    grid(responseRateAx, 'on');
    hold(responseRateAx, 'on');
    
    % Adjust subplot spacing for better layout
    set(customPlotFig, 'Units', 'normalized');
    
    % Add overall title
    sgtitle(customPlotFig, ['Behavior Analysis: ' BpodSystem.GUIData.SubjectName], ...
        'FontSize', 14, 'FontWeight', 'bold', 'Interpreter', 'none');
    
    % Register figure with BpodSystem so it closes when protocol ends
    BpodSystem.ProtocolFigures.CustomPlotFig = customPlotFig;

    % Prepare and start first trial
    genAndLoadStimulus(1);
    [sma, S, updateFlag, ThisITI, QuietTime, correctSide, RewardAmount, TrialInfo] = PrepareStateMachine(S, 1, updateFlag);

    % Store trial parameters before starting the trial
    BpodSystem.Data.ThisITI(1) = ThisITI;
    BpodSystem.Data.QuietTime(1) = QuietTime;
    BpodSystem.Data.CorrectSide(1) = correctSide;
    BpodSystem.Data.RewardAmount(1) = RewardAmount;
    BpodSystem.Data.IsCatchTrial(1) = TrialInfo.IsCatchTrial;

    displayTrialInfo(1, ThisITI, QuietTime, TrialInfo);
    trialManager.startTrial(sma);

    % Main loop, runs once per trial
    for currentTrial = 1:NumTrials
        if BpodSystem.Status.BeingUsed == 0
            CleanupHiFi();
            return;
        end

        if currentTrial < NumTrials
            genAndLoadStimulus(currentTrial+1);
            [sma, S, updateFlag, NextITI, NextQuietTime, NextCorrectSide, NextRewardAmount, NextTrialInfo] = PrepareStateMachine(S, currentTrial+1, updateFlag);

            % Store next trial parameters
            BpodSystem.Data.ThisITI(currentTrial+1) = NextITI;
            BpodSystem.Data.QuietTime(currentTrial+1) = NextQuietTime;
            BpodSystem.Data.CorrectSide(currentTrial+1) = NextCorrectSide;
            BpodSystem.Data.RewardAmount(currentTrial+1) = NextRewardAmount;
            BpodSystem.Data.IsCatchTrial(currentTrial+1) = NextTrialInfo.IsCatchTrial;

            SendStateMachine(sma, 'RunASAP');
        end

        RawEvents = trialManager.getTrialData; % waits until current trial is finished
        if BpodSystem.Status.BeingUsed == 0
            CleanupHiFi();
            return;
        end

        HandlePauseCondition;
        if currentTrial < NumTrials
            trialManager.startTrial();
        end

        % Save trial data and update plots
        if ~isempty(fieldnames(RawEvents))
            BpodSystem.Data = AddTrialEvents(BpodSystem.Data, RawEvents);
            BpodSystem.Data.TrialSettings(currentTrial) = S;
            BpodSystem.Data.TrialStartTimestamp(currentTrial) = RawEvents.TrialStartTimestamp;
            
            % Update trial type for outcome plot based on correct side
            correctSide = BpodSystem.Data.CorrectSide(currentTrial);
            trialTypes(currentTrial) = correctSide; % 1 = left spout, 2 = right spout, 3 = boundary (both)
            
            % Extend trialTypes array to prevent index out of bounds in LiveOutcomePlot
            % The plot window may extend beyond NumTrials, so we need extra elements
            % Calculate maximum possible index: currentTrial + nTrialsToShow - 1
            maxPossibleIndex = currentTrial + outcomePlot.nTrialsToShow - 1;
            if length(trialTypes) < maxPossibleIndex
                % Extend array with default value (1 = left spout) for future trials
                trialTypes(end+1:maxPossibleIndex) = 1;
            end
            
            % Update outcome plot
            outcomePlot.update(trialTypes, BpodSystem.Data);
            
            % Update all plots with layout matching MainAn_v2 combined figure
            try
                PlotSessionSummary(BpodSystem.Data, 'FigureHandle', customPlotFig, 'Axes', summaryAx);
                PlotLickIntervals(BpodSystem.Data, 'FigureHandle', customPlotFig, 'Axes', lickIntervalAx);
                PlotResLatency(BpodSystem.Data, 'FigureHandle', customPlotFig, 'Axes', resLatencyAx);
                PlotLickRaster(BpodSystem.Data, 'FigureHandle', customPlotFig, 'Axes', {rasterAx1, rasterAx2});
                PlotCDFHitRate(BpodSystem.Data, 'FigureHandle', customPlotFig, 'Axes', cdfHitRateAx);
                PlotBarResponse(BpodSystem.Data, 'FigureHandle', customPlotFig, 'Axes', barResponseAx);
                PlotHitResponseRate(BpodSystem.Data, 'FigureHandle', customPlotFig, 'Axes', responseRateAx);
            catch ME
                % Silent error handling - don't let plot errors interrupt the protocol
                disp(['Plot update error: ' ME.message]);
            end

            SaveBpodSessionData;
        end

        HandlePauseCondition;
        if BpodSystem.Status.BeingUsed == 0
            disp('End of session');
            CleanupHiFi();
            return
        end
    end

    % Nested helpers
    function [sma, S, updateFlag, ThisITI, QuietTime, correctSide, RewardAmount, TrialInfo] = PrepareStateMachine(S, currentTrial, updateFlag)
        if updateFlag
            S = BpodParameterGUI('sync', S);
            updateFlag = false;
        end

        % Generate random ITI and quiet time for this trial
        ITIBefore = S.GUI.MinITI/2;
        ITIAfter = S.GUI.MinITI/2 + rand() * (S.GUI.MaxITI - S.GUI.MinITI);
        ThisITI = ITIBefore + ITIAfter;
        QuietTime = S.GUI.MinQuietTime + rand() * (S.GUI.MaxQuietTime - S.GUI.MinQuietTime);
        TimerDuration = ITIAfter + StimDur; % GlobalTimer2 covers stimulus + ITI after
        RewardAmount = S.GUI.RewardAmount;
        ResWin = S.GUI.ResWin;
        CutOff = CutOffPeriod;

        % Get valve times
        ValveTimes = BpodLiquidCalibration('GetValveTimes', RewardAmount, [1 2]);
        LeftValveTime = ValveTimes(1);
        RightValveTime = ValveTimes(2);
        
        % Determine trial conditions from StimTable
        correctSide = StimTable.CorrectSide(currentTrial);
        isRewarded = StimTable.Rewarded(currentTrial);
        isCatchTrial = (StimTable.VibFreq(currentTrial) == 0);

        if correctSide == 1
            correctResponse = 'left';
        elseif correctSide == 2
            correctResponse = 'right';
        elseif correctSide == 3
            correctResponse = 'boundary';
        else
            correctResponse = 'left';
        end

        TrialInfo = struct('ITIBefore', ITIBefore, 'ITIAfter', ITIAfter, 'TimerDuration', TimerDuration, ...
                           'ResWin', ResWin, 'CutOff', CutOff, 'LeftValveTime', LeftValveTime, ...
                           'RightValveTime', RightValveTime, 'CorrectResponse', correctResponse, ...
                           'IsRewarded', isRewarded, 'IsCatchTrial', isCatchTrial);

        % Build state machine
        sma = NewStateMachine();

        % Lick conditions
        sma = SetCondition(sma, 1, 'Port1', 0);
        sma = SetCondition(sma, 2, 'Port2', 0);
        sma = SetCondition(sma, 3, 'Port1', 1);
        sma = SetCondition(sma, 4, 'Port2', 1);

        % Cut-off
        sma = SetGlobalTimer(sma, 'TimerID', 1, 'Duration', CutOff);
        sma = SetCondition(sma, 5, 'GlobalTimer1', 0);

        % Ready / NoLick
        if ITIBefore-QuietTime > 0
            sma = AddState(sma, 'Name', 'Ready', ...
                'Timer', ITIBefore-QuietTime, ...
                'StateChangeConditions', {'Tup', 'NoLick'}, ...
                'OutputActions', {'GlobalTimerTrig', 1});
            sma = AddState(sma, 'Name', 'NoLick', ...
                'Timer', QuietTime, ...
                'StateChangeConditions', {'Port1In', 'ResetNoLick','Port2In', 'ResetNoLick','Tup', 'Stimulus','Condition5', 'Stimulus'}, ...
                'OutputActions', {});
            sma = AddState(sma, 'Name', 'ResetNoLick', ...
                'Timer', 0, ...
                'StateChangeConditions', {'Condition1', 'NoLick','Condition2', 'NoLick','Condition5', 'Stimulus'}, ...
                'OutputActions', {});
        else
            sma = AddState(sma, 'Name', 'Ready', ...
                'Timer', ITIBefore, ...
                'StateChangeConditions', {'Port1In', 'ResetNoLick','Port2In', 'ResetNoLick','Tup', 'Stimulus'}, ...
                'OutputActions', {'GlobalTimerTrig', 1});
            sma = AddState(sma, 'Name', 'NoLick', ...
                'Timer', QuietTime, ...
                'StateChangeConditions', {'Port1In', 'ResetNoLick','Port2In', 'ResetNoLick', 'Tup', 'Stimulus','Condition5', 'Stimulus'}, ...
                'OutputActions', {});
            sma = AddState(sma, 'Name', 'ResetNoLick', ...
                'Timer', 0, ...
                'StateChangeConditions', {'Condition1', 'NoLick','Condition2', 'NoLick','Condition5', 'Stimulus'}, ...
                'OutputActions', {});
        end

        % Trial global timer: stimulus + ITI after
        sma = SetGlobalTimer(sma, 'TimerID', 2, 'Duration', TimerDuration);

        % Stimulus: single playback for StimDur
        sma = AddState(sma, 'Name', 'Stimulus', ...
            'Timer', StimDur, ...
            'StateChangeConditions', {'Tup', 'Response'}, ...
            'OutputActions', {'HiFi1', ['P' 0], 'GlobalTimerTrig', 2});

        % Response mapping
        if isCatchTrial
            sma = AddState(sma, 'Name', 'Response', ...
                'Timer', ResWin, ...
                'StateChangeConditions', {'Port1In', 'Checking', 'Port2In', 'Checking', 'Tup', 'Checking'}, ...
                'OutputActions', {});
        else
            if strcmp(correctResponse, 'left')
                if isRewarded
                    sma = AddState(sma, 'Name', 'Response', ...
                        'Timer', ResWin, ...
                        'StateChangeConditions', {'Port1In', 'LeftReward', 'Port2In', 'WrongChoice', 'Tup', 'Checking'}, ...
                        'OutputActions', {});
                else
                    sma = AddState(sma, 'Name', 'Response', ...
                        'Timer', ResWin, ...
                        'StateChangeConditions', {'Port1In', 'LeftNoReward', 'Port2In', 'WrongChoice', 'Tup', 'Checking'}, ...
                        'OutputActions', {});
                end
            elseif strcmp(correctResponse, 'right')
                if isRewarded
                    sma = AddState(sma, 'Name', 'Response', ...
                        'Timer', ResWin, ...
                        'StateChangeConditions', {'Port1In', 'WrongChoice', 'Port2In', 'RightReward', 'Tup', 'Checking'}, ...
                        'OutputActions', {});
                else
                    sma = AddState(sma, 'Name', 'Response', ...
                        'Timer', ResWin, ...
                        'StateChangeConditions', {'Port1In', 'WrongChoice', 'Port2In', 'RightNoReward', 'Tup', 'Checking'}, ...
                        'OutputActions', {});
                end
            elseif strcmp(correctResponse, 'boundary')
                if isRewarded
                    sma = AddState(sma, 'Name', 'Response', ...
                        'Timer', ResWin, ...
                        'StateChangeConditions', {'Port1In', 'LeftReward', 'Port2In', 'RightReward', 'Tup', 'Checking'}, ...
                        'OutputActions', {});
                else
                    sma = AddState(sma, 'Name', 'Response', ...
                        'Timer', ResWin, ...
                        'StateChangeConditions', {'Port1In', 'LeftNoReward', 'Port2In', 'RightNoReward', 'Tup', 'Checking'}, ...
                        'OutputActions', {});
                end
            end
        end

        % Reward / no reward / wrong choice
        sma = AddState(sma, 'Name', 'LeftReward', ...
            'Timer', LeftValveTime, ...
            'StateChangeConditions', {'Tup', 'DrinkingLeft'}, ...
            'OutputActions', {'ValveState', 1});
        sma = AddState(sma, 'Name', 'RightReward', ...
            'Timer', RightValveTime, ...
            'StateChangeConditions', {'Tup', 'DrinkingRight'}, ...
            'OutputActions', {'ValveState', 2});
        sma = AddState(sma, 'Name', 'WrongChoice', ...
            'Timer', 2, ...
            'StateChangeConditions', {'Tup', 'Checking'}, ...
            'OutputActions', {});
        sma = AddState(sma, 'Name', 'LeftNoReward', ...
            'Timer', 0.5, ...
            'StateChangeConditions', {'Tup', 'DrinkingLeft'}, ...
            'OutputActions', {});
        sma = AddState(sma, 'Name', 'RightNoReward', ...
            'Timer', 0.5, ...
            'StateChangeConditions', {'Tup', 'DrinkingRight'}, ...
            'OutputActions', {});

        % Drinking and grace
        sma = AddState(sma, 'Name', 'DrinkingLeft', ...
            'Timer', 0, ...
            'StateChangeConditions', {'Port1Out', 'DrinkingGrace'}, ...
            'OutputActions', {});
        sma = AddState(sma, 'Name', 'DrinkingRight', ...
            'Timer', 0, ...
            'StateChangeConditions', {'Port2Out', 'DrinkingGrace'}, ...
            'OutputActions', {});
        sma = AddState(sma, 'Name', 'DrinkingGrace', ...
            'Timer', 0.5, ...
            'StateChangeConditions', {'Tup', 'Checking', 'Port1In', 'DrinkingLeft', 'Port2In', 'DrinkingRight'}, ...
            'OutputActions', {});

        % End-of-trial condition (GlobalTimer2 ends)
        sma = SetCondition(sma, 6, 'GlobalTimer2', 0);
        sma = AddState(sma, 'Name', 'Checking', ...
            'Timer', 0, ...
            'StateChangeConditions', {'Condition6', 'exit'}, ...
            'OutputActions', {});
    end

    function genAndLoadStimulus(currentTrial)
        % Generate sound&vibration waveform
        soundWave = GenStimWave(StimTable(currentTrial,:), CalTable);
        soundWave = soundWave(:,1:end-1); % remove last sample for safety
        disp(StimTable(currentTrial,:));

        % Load to HiFi without loop to ensure single playback
        H.load(1, soundWave); % default is single shot
        H.push();
        disp(['Trial ' num2str(currentTrial) ': Sound loaded to buffer 1 (single playback)']);
    end

    function displayTrialInfo(currentTrial, ThisITI, QuietTime, TrialInfo)
        disp(['Trial ' num2str(currentTrial) ': ITI = ' num2str(ThisITI) ' s, QuietTime = ' num2str(QuietTime) ' s']);
        if TrialInfo.IsCatchTrial
            disp(['Trial ' num2str(currentTrial) ': Catch trial']);
        else
            disp(['Trial ' num2str(currentTrial) ': Correct response = ' TrialInfo.CorrectResponse ', Rewarded = ' num2str(TrialInfo.IsRewarded)]);
        end
    end

    % Session cleanup
    function CleanupHiFi()
        try
            H.stop();
        catch
        end
        try
            clear H;
        catch
        end
    end
end